### ISSUE TITLE
Bug in FPGA commander

### ISSUE THREAD

**Issue by BFH-ktt1** [kevinawalsh/logisim-evolution#36]
Wenn creating a circuit and we do not save this circuit, but go directly to the FPGA commander and press Download, logisim generates a null-pointer exception:
 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.bfh.logisim.fpgagui.FPGACommanderGui.DownLoad(FPGACommanderGui.java:864)
due to:

String Dir = MyProject.getLogisimFile().getLoader().getMainFile().toString();
if (Dir.contains(" ")) {
	MyReporter.AddFatalError(S.fmt("FPGADirContainsSpaces", Dir));
...

As no file has been loaded nor saved the getMainFile() will return null.

**Comment by kevinawalsh** [comment]
Thanks for the report.

This one isn't present in my working copy, which is in the middle of a pretty complete overhaul of nearly all of the hdl and fpga code, fixing lots of previously accumulated and newly discovered bugs. But I'm going to leave the issue open so I can circle back later to make sure this bug doesn't crop up again. Not entirely clear what to do with an unsaved project -- probably just warn, since if the file is not saved there is no obvious and polite place on disk to dump all the HDL-related files and synthesis output.
