### ISSUE TITLE
logisim startup warnings

### ISSUE THREAD

**Issue by ronaldmaas** [kevinawalsh/logisim-evolution#73]
Using logisim evolution with openjdk version 15  on Windows 10 gives me some errors/warnings on startup.
Not sure if it is stopping me doing anything, but just wondering what the significance of them is.

C:\electronics\logisim-evolution>java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

C:\electronics\logisim-evolution>java -jar logisim-evolution-4.0.4hc.jar
Note [2]: no support to control quit strategy and handler
Note [3]: no support for desktop file opening
Note [4]: no support for desktop file printing
Note [5]: no support for desktop preferences
Note [6]: no support for desktop about screen
Note [7]: no desktop menubar support

C:\electronics\logisim-evolution>

**Comment by kevinawalsh** [comment]
If you use the ".exe" version for windows (download link is available on the github page), then you shouldn't see those warnings or any other warnings, for that matter, since the terminal will not be visible.

For the ".jar" version, those messages are harmless. They concern desktop integration which currently works only on Mac. I should take those messages out, but those have been a nice reminder to me to fix the desktop integration.
