### ISSUE TITLE
Feature Request : "UP" button while in circuit simulation

### ISSUE THREAD

**Issue by John-Lluch** [kevinawalsh/logisim-evolution#95]
While in simulation mode, most notably when I am performing "manual tick" step-by-step simulations, I tend to double-click on sub-circuits to open them in order to assess their internal state at specific times during the simulation. This is a nice feature that allows me to narrow down project issues or check behavior for a better understanding.

However, after opening a sub-circuit I would like a quick way to return to its parent circuit. A "back" (or "up") button on the simulate panel, would be very useful to navigate projects in a quicker and more intuitive way.

Please note that this request is not about keeping a navigation history like internet browsers do, as I understand that would be a complex and time consuming task and not that useful after all, but just a quick way to navigate to the "parent" circuit on the project simulation hierarchy. 

I believe this feature would improve user experience particularly during simulations.

Thanks

**Comment by kevinawalsh** [comment]
I hope commit a43ae5f6c8e476e222e317305967b79fc351efa4 should address this.

There has always been menu items (look under the "Simulate" menu) for moving up and down the simulation hierarchy, and shortcuts Control-Left and Control-Right as well (on mac: Command-Left, Command-Right). But admittedly, these menu items and shortcuts were not obvious, I didn't even remember them myself. Also, keyboard navigation within the simualtion tree on the left sidebar was broken: up/down arrows didn't work, etc.

This new commit changes the shortcuts to "Control-Up" and "Control-Down" (mac: Command-Up, Command-Down), which is probably much more intuitive, it fixes keyboard navigation, and you can hit "space" and "enter" to switch to the selected simulation.

I didn't add a separate icon/button in the toolbar, because my first instinct would be to use up/down arrow icons and those would look exactly like the up/down arrows in the project explorer, which do something different (they move the circuit up or down in the list). Instead, perhaps one or both of these might be an idea instead:
 - add buttons that resemble zoom-in / zoom-out to the simulation toolbar
 - add a mini-map to the main window when looking at the simulation tree (much like the mini-map when using dynamic appearance elements in the appearance editor). This would pop up in the bottom right corner, showing a miniature view of the parent circuit and highlighting where the current simulation component is within that parent circuit.
 
I prototyped the second option, and it looks nice, but the interface still needs work -- the mini window would need to be able to be moved/resized/closed, etc., and it needs to pop up only in certain cases.

I'm closing this for now, as I hope the current commit is good enough for a while.
